" ~/.vimrc

set nocompatible
set cursorline
set formatoptions=tcqr
set laststatus=2
set listchars=eol:¬,tab:▸\ ,trail:.,precedes:<,extends:>
set ruler
set scrolloff=10
set whichwrap=<,>,h,l
set wildmenu

set autoindent smartindent
set expandtab softtabstop=4 tabstop=4 shiftwidth=4 shiftround nowrap
set ignorecase incsearch infercase smartcase
set number numberwidth=4
set textwidth=78 colorcolumn=+1
set virtualedit=all

syntax on
filetype indent on
filetype plugin on

function! s:TrimWhitespace()
  if !getbufvar('%', '&modifiable')
    return
  endif
  let s:view = winsaveview()
  try
    silent! keeppatterns keepjumps %s/\s\+$//e
    silent! keeppatterns keepjumps %s/\n\+\%$//e
  finally
    call winrestview(s:view)
  endtry
endfunction

augroup vimrc
  autocmd!
  autocmd BufWritePre,FileWritePre * :call s:TrimWhitespace()
augroup end

" plugin: fzf
let &runtimepath .= ',' . fnameescape($HOMEBREW_PREFIX . '/opt/fzf')

" plugin: catpuccing
set termguicolors
colorscheme catppuccin_mocha

" plugin: lightline
set noshowmode
let g:lightline = {'colorscheme': 'catppuccin_mocha'}

let mapleader = " "
nnoremap <leader>cd :Ex<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>ff :Files<CR>
nnoremap <leader>fh :Helptags<CR>
nnoremap <leader>gi :Rg<Space>

if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
