" ~/.vimrc

set cursorline
set formatoptions=tcqr
set laststatus=2
set listchars=eol:¬,tab:▸\ ,trail:.,precedes:<,extends:>
set ruler
set scrolloff=10
set whichwrap=<,>,h,l
set wildmenu

set autoindent smartindent
set backupdir=~/.vim/tmp/backup// directory=~/.vim/tmp/swap// undodir=~/.vim/tmp/undo//
set expandtab softtabstop=4 tabstop=4 shiftwidth=4 shiftround nowrap
set ignorecase incsearch infercase smartcase
set number numberwidth=4
set textwidth=78 colorcolumn=+1
set virtualedit=all

function! s:TrimWhitespace()
  if !getbufvar('%', '&modifiable')
    return
  endif

  let s:view = winsaveview()
  try
    silent! keeppatterns keepjumps %s/\s\+$//e
    silent! keeppatterns keepjumps %s/\n\+\%$//e
  finally
    call winrestview(s:view)
  endtry
endfunction

augroup vimrc
  autocmd!
  autocmd BufWritePre,FileWritePre * :call s:TrimWhitespace()
augroup end

call plug#begin()
  Plug 'catppuccin/vim', { 'as': 'catppuccin' }
  Plug 'itchyny/lightline.vim'
  Plug 'editorconfig/editorconfig-vim'
call plug#end()

set termguicolors
colorscheme catppuccin_mocha

set noshowmode
let g:lightline = {'colorscheme': 'catppuccin_mocha'}

if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
